create table if not exists public.orders (
  id text primary key,
  date timestamptz not null default now(),
  agent_name text not null,
  customer_name text,
  customer_phone text,
  delivery_area text,
  godown_location text not null,
  whatsapp_group text,
  status text not null default 'New'
    check (status in ('New', 'Packed', 'Dispatched', 'Delivered')),
  notes text,
  items jsonb not null default '[]'::jsonb,
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now()
);

alter table public.orders enable row level security;

drop policy if exists "Logged in users can read orders" on public.orders;
create policy "Logged in users can read orders"
on public.orders
for select
to authenticated
using (true);

drop policy if exists "Logged in users can create orders" on public.orders;
create policy "Logged in users can create orders"
on public.orders
for insert
to authenticated
with check (true);

drop policy if exists "Logged in users can update orders" on public.orders;
create policy "Logged in users can update orders"
on public.orders
for update
to authenticated
using (true)
with check (true);

drop policy if exists "Logged in users can delete orders" on public.orders;
create policy "Logged in users can delete orders"
on public.orders
for delete
to authenticated
using (true);

create table if not exists public.godown_stocks (
  id bigint generated by default as identity primary key,
  godown_location text not null,
  product text not null,
  color text not null default '',
  quantity integer not null default 0 check (quantity >= 0),
  updated_by uuid default auth.uid(),
  updated_at timestamptz not null default now(),
  unique (godown_location, product, color)
);

alter table public.godown_stocks enable row level security;

drop policy if exists "Logged in users can read stock" on public.godown_stocks;
create policy "Logged in users can read stock"
on public.godown_stocks
for select
to authenticated
using (true);

drop policy if exists "Logged in users can create stock" on public.godown_stocks;
create policy "Logged in users can create stock"
on public.godown_stocks
for insert
to authenticated
with check (true);

drop policy if exists "Logged in users can update stock" on public.godown_stocks;
create policy "Logged in users can update stock"
on public.godown_stocks
for update
to authenticated
using (true)
with check (true);

drop trigger if exists set_godown_stocks_updated_at on public.godown_stocks;
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  new.updated_by = auth.uid();
  return new;
end;
$$;

create trigger set_godown_stocks_updated_at
before update on public.godown_stocks
for each row
execute function public.set_updated_at();
